// Crop sprites (ART_STYLE.md §2): `crop_<id>_<stage>` for stages 0–4, drawn over the soil tile with
// a transparent background, plus `crop_dead` for every withered crop.
//
// Authoring: the ready stage (4) of each crop is a hand-drawn fill that `outlined()` rings in
// `outline`. Stage 3 (near-ready) is the ready sprite with its produce recoloured: fruit is still
// green, roots are still soil mounds. Stages 0–2 come from a few shared shapes per plant form.
// Ready crops get a second frame with a sparkle (2 frames, 400 ms).

import { CROP_IDS, type CropId } from '../../data/ids';
import { outlined, recolored, sparkled, type SpriteDef } from './types';

type Form = 'leafy' | 'bush' | 'stalk' | 'stake' | 'vine';

interface CropArt {
  form: Form;
  /** The seed colour shown at stage 0. */
  seed: string;
  /** Ready stage, as a fill (the outline is added). */
  ready: readonly string[];
  /** Recolour map for the near-ready stage. */
  unripe: Readonly<Record<string, string>>;
}

const ART: Record<CropId, CropArt> = {
  turnip: {
    form: 'leafy',
    seed: 'x',
    ready: [
      '................',
      '......k...k.....',
      '.....kGk.kGk....',
      '....kGHGkGHGk...',
      '....kgGGkGGgk...',
      '.....kgGGGgk....',
      '......klGlk.....',
      '.....kvVvvvk....',
      '....kvVVvvvvk...',
      '....kxwxxxxxk...',
      '....kwxxxxxxk...',
      '.....kxxxxxk....',
      '......kxxxk.....',
      '.......kxk......',
      '........k.......',
      '................',
    ],
    unripe: { v: 'S', V: 'S', x: 's', w: 'S' },
  },
  potato: {
    form: 'leafy',
    seed: 'P',
    ready: [
      '................',
      '................',
      '.....G...G......',
      '....GHG.GHG.G...',
      '...gGGGgGGGgHG..',
      '...gGlGGGlGGg...',
      '....gGGlGgGg....',
      '......glGg......',
      '.......lg.......',
      '...PPPklkPPP....',
      '..PPPPpkPPPPp...',
      '..PMPPpkPMPPp...',
      '..pPPppkpPPpp...',
      '...pppk.kppp....',
      '................',
      '................',
    ],
    unripe: { P: 'S', p: 's', M: 's' },
  },
  garlic: {
    form: 'stalk',
    seed: 'x',
    ready: [
      '................',
      '................',
      '........G.......',
      '....G...G...G...',
      '....G...G..G....',
      '.....G..G.G.....',
      '......GGGG......',
      '.......GG.......',
      '.......GG.......',
      '......xwxx......',
      '.....xwxxVx.....',
      '....xwxxVxxx....',
      '....xxxVxxxy....',
      '.....xxVxxy.....',
      '......yyyy......',
      '................',
    ],
    unripe: { x: 'S', w: 'S', V: 's', y: 's' },
  },
  strawberry: {
    form: 'bush',
    seed: 'y',
    ready: [
      '................',
      '................',
      '................',
      '................',
      '......GGGG......',
      '....GGHGGHGG....',
      '...GHGQqGGgGG...',
      '..gGGqqgGGQqGg..',
      '..gGgGqgGgqqgG..',
      '..GQqgGGHGgqGg..',
      '..gqqgGGGGgGQq..',
      '...gqgGgGgGgqq..',
      '...gglgglgggl...',
      '................',
      '................',
      '................',
    ],
    unripe: { q: 'H', Q: 'L' },
  },
  cauliflower: {
    form: 'leafy',
    seed: 'x',
    ready: [
      '................',
      '................',
      '................',
      '................',
      '......wwxx......',
      '.....wxxwxxy....',
      '.GG.xxxxxwxy.GG.',
      'GHGkxwxxxxyykGHG',
      'gGGGkyxxxyykGGGg',
      '.gGGGkkkkkkGGGg.',
      '.gglGGGgGGGlggg.',
      '..gglGgGgGlggg..',
      '...gglglglgg....',
      '................',
      '................',
      '................',
    ],
    unripe: { x: 'G', w: 'H', y: 'g' },
  },
  wheat: {
    form: 'stalk',
    seed: 'Y',
    ready: [
      '................',
      '.......U........',
      '...U...u....U...',
      '...u..yuy...u...',
      '..yuy.uyu..yuy..',
      '..uyu.yuy..uyu..',
      '..yuy.uyu..yuy..',
      '...Y..yuy...Y...',
      '...Y...Y...Y....',
      '...Y...Y..GY....',
      '..GY...YG.Y.....',
      '...YG..Y..Y.....',
      '....Y..Y.Y......',
      '....YY.YYY......',
      '.....YYYY.......',
      '................',
    ],
    unripe: { U: 'H', u: 'G', y: 'H', Y: 'g' },
  },
  tomato: {
    form: 'stake',
    seed: 'P',
    ready: [
      '................',
      '.......M........',
      '.....GGMGG......',
      '....GHGMGHG.....',
      '...GQqGMGGG.....',
      '...GqqGMGQqG....',
      '....GGgMGqqG....',
      '...GGHGMGgG.....',
      '..GQqGGMGGQq....',
      '..GqqgGMGgqq....',
      '...GgGGMGGgG....',
      '....ggGMGgg.....',
      '.......M........',
      '.......m........',
      '................',
      '................',
    ],
    unripe: { q: 'G', Q: 'H' },
  },
  blueberry: {
    form: 'bush',
    seed: 'j',
    ready: [
      '................',
      '................',
      '................',
      '................',
      '.....GGHGGH.....',
      '....GHGJjGGGG...',
      '..GGGgjjGgJJgG..',
      '..gJjGgGGgjjgG..',
      '..gjjgGJjGGgGg..',
      '..GGgGgjjgGJjG..',
      '..gGJJgGGgGjjg..',
      '...gjjgGgJjgg...',
      '....glglgjjg....',
      '................',
      '................',
      '................',
    ],
    unripe: { j: 'H', J: 'L' },
  },
  corn: {
    form: 'stalk',
    seed: 'u',
    ready: [
      '................',
      '.......G........',
      '.......G........',
      '....G..G..G.....',
      '....GG.G.GG.....',
      '.....GGGGG......',
      '.......GUu......',
      '...GG..GuUu.....',
      '..GG..GGUuU.....',
      '.....GGGuUu.....',
      '.......GUuU.....',
      '.......GGUG.GG..',
      '.......GGgGGG...',
      '.......GGGG.....',
      '.......glg......',
      '................',
    ],
    unripe: { U: 'H', u: 'G' },
  },
  melon: {
    form: 'vine',
    seed: 'Y',
    ready: [
      '................',
      '................',
      '................',
      '................',
      '..GG........GG..',
      '.GHGG..G...GGHG.',
      '..GGgkGgk.kgGG..',
      '....kHHGGGGGk...',
      '...kHGlGGlGGlk..',
      '...kGlGGlGGlGk..',
      '...kGlGGlGGlgk..',
      '...kglGglGglgk..',
      '....kggGggGgk...',
      '.....kkkkkkk....',
      '................',
      '................',
    ],
    unripe: { H: 'L', G: 'H', g: 'G', l: 'g', h: 'g' },
  },
  yam: {
    form: 'leafy',
    seed: 'o',
    ready: [
      '................',
      '................',
      '................',
      '.....G....G.....',
      '....GHG..GHG....',
      '....gGGllGGg....',
      '.....gGllGg.....',
      '.......ll.......',
      '.......ll.......',
      '...QOOOOooo.....',
      '..OOOOooooooo...',
      '..OoOoooooooq...',
      '...ooooooooq....',
      '.....qqqq.......',
      '................',
      '................',
    ],
    unripe: { Q: 'S', O: 'S', o: 's', q: 's' },
  },
  kale: {
    form: 'leafy',
    seed: 'y',
    ready: [
      '................',
      '................',
      '.....G.G.G.G....',
      '....GHGkGHGkG...',
      '...gGlGkGlGkGg..',
      '..gGlGGkGlGGlGg.',
      '..glGgkGGkgGlg..',
      '..gGlgkGHGkglGg.',
      '.glGllkGGGkllGlg',
      '..gllGgkGkgGllg.',
      '...glllgvglllg..',
      '....gllvvvllg...',
      '......gvvvg.....',
      '................',
      '................',
      '................',
    ],
    unripe: { l: 'g', v: 'G' },
  },
  cranberry: {
    form: 'bush',
    seed: 'q',
    ready: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '.....ggGGgg.....',
      '...gGqQgGqQgg...',
      '..gGQqGgqqGgGg..',
      '..Gqqgqq.gGQqg..',
      '..glGgqqgQqqlg..',
      '..gQqlggGqqgGg..',
      '..gqqgQqGglQqg..',
      '...gllgqqlgqq...',
      '................',
      '................',
      '................',
    ],
    unripe: { q: 'G', Q: 'H' },
  },
  pumpkin: {
    form: 'vine',
    seed: 'x',
    ready: [
      '................',
      '................',
      '................',
      '................',
      '.......mM..GG...',
      '.......mM.GHG...',
      '...GG..Mm..G....',
      '..OOOOkOOOkOO...',
      '.OOOOoOOOoOOOo..',
      '.OOOoOOOoOOOoo..',
      '.OOooOOooOOooo..',
      '.oOooOooooOooo..',
      '..ooooooooooo...',
      '................',
      '................',
      '................',
    ],
    unripe: { O: 'H', o: 'G' },
  },
  leek: {
    form: 'stalk',
    seed: 'x',
    ready: [
      '................',
      '..G....G....G...',
      '...G...G...G....',
      '...lG..H..Gl....',
      '....lGGHGGl.....',
      '......GHG.......',
      '......LHL.......',
      '......LxL.......',
      '......xwx.......',
      '......xwx.......',
      '......xwx.......',
      '......xwx.......',
      '......xxy.......',
      '......xxy.......',
      '................',
      '................',
    ],
    unripe: { x: 'L', w: 'H', y: 'G' },
  },
};

/** Stage 1: a sprout. Leafy crops get two leaves, stalk crops a pair of blades. */
const SPROUT: Record<'leaf' | 'blade', readonly string[]> = {
  leaf: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.....HG..GH.....',
    '.....GHGGHG.....',
    '.......GG.......',
    '.......gg.......',
    '................',
    '................',
    '................',
  ],
  blade: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.......H........',
    '.......H..H.....',
    '.....H.G.H......',
    '......GGG.......',
    '.......gg.......',
    '................',
    '................',
    '................',
  ],
};

/** Stage 2: mid-growth, by plant form. */
const MID: Record<Form, readonly string[]> = {
  leafy: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '......G..G......',
    '.....GHGGHG.....',
    '....GHGgGGHG....',
    '....gGGlGGGg....',
    '.....gGllGg.....',
    '.......ll.......',
    '.......gg.......',
    '................',
    '................',
    '................',
  ],
  bush: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '......GHGG......',
    '....GHGGHGGG....',
    '...gGGgGGgGGg...',
    '...gGlGGlGGlg...',
    '....gglgglgg....',
    '................',
    '................',
    '................',
    '................',
  ],
  stalk: [
    '................',
    '................',
    '................',
    '................',
    '.......G........',
    '....G..G..G.....',
    '....G..G..G.....',
    '.....G.G.G......',
    '.....G.H.G......',
    '......GGG.......',
    '......GHG.......',
    '.......G........',
    '.......gg.......',
    '................',
    '................',
    '................',
  ],
  stake: [
    '................',
    '................',
    '................',
    '................',
    '.......M........',
    '......GMG.......',
    '.....GHMGG......',
    '....GGgMGHG.....',
    '.....GGMGg......',
    '....GHGMGG......',
    '.....ggMgg......',
    '.......M........',
    '.......m........',
    '................',
    '................',
    '................',
  ],
  vine: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..GG.......GG...',
    '.GHG...G...GHG..',
    '..GGG.GHG.GGG...',
    '....GGGgGGG.....',
    '......glg.......',
    '................',
    '................',
    '................',
    '................',
  ],
};

/** Stage 0: a patted-down mound with the seeds showing. Not outlined: it is part of the soil. */
function seedStage(seed: string): string[] {
  return [
    ...Array.from({ length: 10 }, () => '................'),
    '......d..d......',
    `.....dS${seed}SS${seed}d....`,
    `....dSs${seed}ss${seed}Sd...`,
    '.....dddddd.....',
    '................',
    '................',
  ];
}

function cropStages(id: CropId): SpriteDef[] {
  const art = ART[id];
  const ready = outlined(art.ready);
  const sprout = art.form === 'stalk' ? SPROUT.blade : SPROUT.leaf;
  const stage = (n: number, frames: string[][], frameMs?: number): SpriteDef => ({
    id: `crop_${id}_${n}`,
    anchor: 'bottom-center',
    frames,
    ...(frameMs ? { frameMs } : {}),
  });
  return [
    stage(0, [seedStage(art.seed)]),
    stage(1, [outlined(sprout)]),
    stage(2, [outlined(MID[art.form])]),
    stage(3, [recolored(ready, art.unripe)]),
    stage(4, [ready, sparkled(ready)], 400),
  ];
}

/** A withered crop: a drooping brown stalk (the same sprite for every crop). */
const cropDead: SpriteDef = {
  id: 'crop_dead',
  anchor: 'bottom-center',
  frames: [
    outlined([
      '................',
      '................',
      '................',
      '................',
      '................',
      '.........MM.....',
      '...Mm...M..m....',
      '....mM..M.......',
      '.....mM.M..Mm...',
      '......mMm.Mm....',
      '..mM...Mm.m.....',
      '...mmM.mMm......',
      '.....mmMM.......',
      '......mMm.......',
      '................',
      '................',
    ]),
  ],
};

export const CROP_SPRITES: readonly SpriteDef[] = [...CROP_IDS.flatMap(cropStages), cropDead];
