// Inventory icons (ART_STYLE.md §2): `item_<crop>` for each harvested crop and `item_seed_<crop>`
// for its seed packet. Icons are fills ringed by `outlined()`; each should read from its
// silhouette alone at 16 × 16.

import { CROP_IDS, type CropId } from '../../data/ids';
import { outlined, recolored, shifted, type SpriteDef } from './types';

interface IconArt {
  fill: readonly string[];
  dx?: number;
  dy?: number;
}

const CROP_ICONS: Record<CropId, IconArt> = {
  turnip: {
    fill: [
      '................',
      '......G.G.......',
      '.....GHkGG......',
      '......GGG.......',
      '.....vVvvv......',
      '....vVVvvvv.....',
      '...vVvvvvvvv....',
      '...xwxxxxxxx....',
      '...wxxxxxxxx....',
      '...xxxxxxxxy....',
      '....xxxxxxy.....',
      '.....xxxxy......',
      '......xxy.......',
      '.......x........',
      '................',
      '................',
    ],
    dx: 1,
  },
  potato: {
    fill: [
      '................',
      '................',
      '................',
      '................',
      '.....PPPPP......',
      '...PPyPPPPPP....',
      '..PPPPPPMPPPp...',
      '..PMPPPPPPPPpp..',
      '..PPPPPPPPPMpp..',
      '..pPPPMPPPPppp..',
      '...pPPPPPPppp...',
      '....ppppppp.....',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  garlic: {
    fill: [
      '................',
      '.......G........',
      '.......G........',
      '......xwx.......',
      '.....xwxxx......',
      '....xwxVxxx.....',
      '...xwxxVxxVx....',
      '...wxxVxxxVx....',
      '...xxxVxxVxy....',
      '...xxVxxxVxy....',
      '....xxxxxxy.....',
      '.....yYyYy......',
      '................',
      '................',
      '................',
      '................',
    ],
    dx: 1,
    dy: 1,
  },
  strawberry: {
    fill: [
      '................',
      '................',
      '.....GG.GG......',
      '....GHGGGGG.....',
      '...QQqGGqqqq....',
      '..QQwQqqqqqqq...',
      '..QwQqqqUqqqq...',
      '..QQqUqqqqqqr...',
      '...qqqqqqUqr....',
      '...qUqqqqqqr....',
      '....qqqUqqr.....',
      '.....qqqqr......',
      '......qqr.......',
      '.......r........',
      '................',
      '................',
    ],
    dx: 1,
  },
  cauliflower: {
    fill: [
      '................',
      '................',
      '................',
      '.....wwxxx......',
      '....wxxwxxxy....',
      '...wxxxxxwxxy...',
      '...xwxxwxxxxy...',
      '..GkxxxxxxyykG..',
      '.GHGkyxxyyykGHG.',
      '.gGGGkkkkkkGGGg.',
      '..gGGGgGGgGGGg..',
      '...ggGGgGGgGg...',
      '.....gglggg.....',
      '................',
      '................',
      '................',
    ],
  },
  wheat: {
    fill: [
      '................',
      '...U...U...U....',
      '..UuU.UuU.UuU...',
      '..uyu.uyu.uyu...',
      '..yuy.yuy.yuy...',
      '..uyu.uyu.uyu...',
      '...Yy.yYy.yY....',
      '....Yy.Y.yY.....',
      '.....YyYyY......',
      '......qQq.......',
      '.....YyYyY......',
      '....Yy.Y.yY.....',
      '...Yy..Y..yY....',
      '...Y...Y...Y....',
      '................',
      '................',
    ],
    dx: 1,
  },
  tomato: {
    fill: [
      '................',
      '................',
      '................',
      '......GkG.......',
      '.....GHGGG......',
      '...qqkGGkqq.....',
      '..qQQqkkqqqq....',
      '.qQwQqqqqqqqq...',
      '.qQQqqqqqqqqr...',
      '.qQqqqqqqqqqr...',
      '.qqqqqqqqqqrr...',
      '..qqqqqqqqrr....',
      '...rrrrrrrr.....',
      '................',
      '................',
      '................',
    ],
    dx: 1,
  },
  blueberry: {
    fill: [
      '................',
      '.........GG.....',
      '........GHG.....',
      '.......GG.......',
      '....JJj..JJj....',
      '...JwJjj.wJjj...',
      '...JJjjj.Jjjj...',
      '...jjjjb.jjjb...',
      '....jjb..jjb....',
      '......JJj.......',
      '.....JwJjj......',
      '.....JJjjj......',
      '.....jjjjb......',
      '......jjb.......',
      '................',
      '................',
    ],
  },
  corn: {
    fill: [
      '................',
      '.........G......',
      '........GU......',
      '.......UuU......',
      '......UuUu......',
      '.....UuUuU......',
      '....GuUuUu......',
      '...GGUuUuG......',
      '..GHGuUuGG......',
      '..GGGUuGGl......',
      '...GGGGGl.......',
      '....GGGl........',
      '.....gl.........',
      '................',
      '................',
      '................',
    ],
    dx: 2,
    dy: 1,
  },
  melon: {
    fill: [
      '................',
      '................',
      '................',
      '................',
      '.......m........',
      '.....GHGGG......',
      '...HGGlGGlGG....',
      '..HGlGGlGGlGG...',
      '..GGlGGlGGlGg...',
      '..GglGGlGGlgg...',
      '..gglGglGglgg...',
      '...ggGggGggg....',
      '.....ggggg......',
      '................',
      '................',
      '................',
    ],
    dx: 1,
  },
  yam: {
    fill: [
      '................',
      '................',
      '................',
      '................',
      '.........Gg.....',
      '......QOOGG.....',
      '....QOOOOoo.....',
      '...QOOOoooooq...',
      '..OOOoooooooq...',
      '..OoOooooooq....',
      '...ooooooqq.....',
      '....ooqqq.......',
      '................',
      '................',
      '................',
      '................',
    ],
    dx: 1,
  },
  kale: {
    fill: [
      '................',
      '.....G.G.G......',
      '....GHGkGHG.....',
      '...gGlGkGlGg....',
      '..gGlGGkGGlGg...',
      '..glGgkGkgGlg...',
      '..gGlgkGkglGg...',
      '...gllgkgllg....',
      '....gllvllg.....',
      '.....glvlg......',
      '......gvg.......',
      '.......v........',
      '.......v........',
      '................',
      '................',
      '................',
    ],
    dx: 1,
    dy: 1,
  },
  cranberry: {
    fill: [
      '................',
      '................',
      '................',
      '.........GG.....',
      '........GHG.....',
      '.....Qq.G.......',
      '....QwqqQq......',
      '....qqqrwqq.....',
      '.....qrqqqr.....',
      '...Qq.Qq.rQq....',
      '..Qwqqwqq.wqq...',
      '..qqqrqqr.qqr...',
      '...qr..qr..r....',
      '................',
      '................',
      '................',
    ],
    dx: 1,
  },
  pumpkin: {
    fill: [
      '................',
      '................',
      '................',
      '.......mM.......',
      '.......Mm..G....',
      '...OOOOkOOGHG...',
      '..OOOoOOOoOOO...',
      '.OOOoOOOoOOOoo..',
      '.OOooOOooOOooo..',
      '.OOooOOooOOooo..',
      '.oOooOooooOooo..',
      '..ooooooooooo...',
      '...ooooooooo....',
      '................',
      '................',
      '................',
    ],
    dx: 1,
  },
  leek: {
    fill: [
      '................',
      '..G.....G.......',
      '...G...G........',
      '...lG.GH........',
      '....lGHG........',
      '.....GHG........',
      '.....LHL........',
      '.....LxL........',
      '.....xwx........',
      '.....xwx........',
      '.....xwx........',
      '.....xwx........',
      '.....xxy........',
      '.....xxy........',
      '................',
      '................',
    ],
    dx: 2,
  },
};

/** Seed packet: kraft paper with a blob of the crop's colour (1), highlight (2) and shade (3). */
const PACKET: readonly string[] = [
  '................',
  '................',
  '...PpPpPpPpPp...',
  '...PPPPPPPPPp...',
  '...PPPPGGPPPp...',
  '...PPPPPGPPPp...',
  '...PPP211PPPp...',
  '...PP21111PPp...',
  '...PP111113Pp...',
  '...PPP1113PPp...',
  '...PPPP33PPPp...',
  '...PPPPPPPPPp...',
  '...PPPPPPPPPp...',
  '...pppppppppp...',
  '................',
  '................',
];

const PACKET_COLOURS: Record<CropId, readonly [string, string, string]> = {
  turnip: ['V', 'v', 'x'],
  potato: ['S', 's', 'd'],
  garlic: ['w', 'x', 'V'],
  strawberry: ['I', 'Q', 'q'],
  cauliflower: ['w', 'x', 'y'],
  wheat: ['U', 'u', 'Y'],
  tomato: ['Q', 'q', 'r'],
  blueberry: ['J', 'j', 'b'],
  corn: ['U', 'u', 'F'],
  melon: ['H', 'G', 'l'],
  yam: ['O', 'o', 'r'],
  kale: ['g', 'l', 'h'],
  cranberry: ['q', 'r', 'K'],
  pumpkin: ['O', 'o', 'F'],
  leek: ['L', 'H', 'x'],
};

function cropIcon(id: CropId): SpriteDef {
  const art = CROP_ICONS[id];
  return { id: `item_${id}`, frames: [outlined(shifted(art.fill, art.dx ?? 0, art.dy ?? 0))] };
}

function seedPacket(id: CropId): SpriteDef {
  const [light, main, shade] = PACKET_COLOURS[id];
  const colours = { '1': main, '2': light, '3': shade };
  return { id: `item_seed_${id}`, frames: [outlined(recolored(PACKET, colours))] };
}

export const ITEM_SPRITES: readonly SpriteDef[] = [...CROP_IDS.map(cropIcon), ...CROP_IDS.map(seedPacket)];
