// Objects and buildings, outlined with `k` and lit from the top-left (ART_STYLE.md §2).
// The farmhouse, market stall and tree are larger than one tile and are single grids.

import type { SpriteDef } from './types';

/** 4 × 3 tiles; fills the Farmhouse zone (1,1)–(4,3). */
export const objFarmhouse: SpriteDef = {
  id: 'obj_farmhouse',
  anchor: 'top-left',
  frames: [
    [
      '...........................................kKnnnnnnnKk..........',
      '...........................................kKKKKKKKKKk..........',
      '............................................kNnnnnnnk...........',
      '............................................kNnnnnnnk...........',
      '...................kkkkkkkkkkkkkkkkkkkkkkkkkkNKKKKKKk...........',
      '..................kQQQQQQQQQQQQQQQQQQQQQQQQQQNnnnnnnk...........',
      '.................krRRRRRrRRRRRrRRRRRrRRRRRrRRrnnnnnnk...........',
      '................krrRRRRRrRRRRRrRRRRRrRRRRRrRRRrKKKKKk...........',
      '...............krrRrrrrrRrrrrrRrrrrrRrrrrrRrrrrrnnnnk...........',
      '..............krRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRrnnnk...........',
      '.............krrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRrKKk...........',
      '............krRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRrnk...........',
      '...........krrrRrrrrrRrrrrrRrrrrrRrrrrrRrrrrrRrrrrrrk...........',
      '..........krrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRrk..........',
      '.........krRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRrk.........',
      '........krRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrk........',
      '.......krrrrRrrrrrRrrrrrRrrrrrRrrrrrRrrrrrRrrrrrRrrrrrRrk.......',
      '......krRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRrk......',
      '.....krRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrk.....',
      '....krRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrrk....',
      '...krrrrrRrrrrrRrrrrrRrrrrrRrrrrrRrrrrrRrrrrrRrrrrrRrrrrrRrrk...',
      '.kkrRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrkk.',
      'krrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrk',
      'kKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk',
      '.kkkpMppppppppppppppppppppppppppppppppppppppppppppppppppppmmkkk.',
      '...kpMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmk...',
      '...kpMPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPmmk...',
      '...kpMpppppppppppppppppppppppppPPPPPPPPPPpppppPPPPPPPPPPppmmk...',
      '...kpMpppppppppppppppppppppppppPccccPcccPpppppPccccPcccPppmmk...',
      '...kpMMMMMMMmmmmmmmmmmmMKKMMMMMPcCCcPcccPMMMMMPcCCcPcccPMMmmk...',
      '...kpMPPPPPPmpppppppppmPUOPPPPPPcCccPcccPPPPPPPcCccPcccPPPmmk...',
      '...kpMppppppmMpMpMpMpMmpOOpppppPPPPPPPPPPpppppPPPPPPPPPPppmmk...',
      '...kpMppppppmMpMpMpMpMmpOOpppppPBBBBPBBBPpppppPBBBBPBBBPppmmk...',
      '...kpMMMMMMMmMpMpMpMpMmMMMMMMMMPBBBBPBBBPMMMMMPBBBBPBBBPMMmmk...',
      '...kpMPPPPPPmMpMpMpMpMmPPPPPPPPPqBBBuBBBiPPPPPPqBBBuBBBiPPmmk...',
      '...kpMppppppmMpMpMpMpMmppppppppPGgGgGgGgGgppppPGgGgGgGgGgpmmk...',
      '...kpMppppppmMpMpMpMpMmpppppppppppppppppppppppppppppppppppmmk...',
      '...kpMMMMMMMmMpMpMpMfMmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmk...',
      '...kpMPPPPPPmMpMpMpMFMmPPPPPPPmmmmmmmmmmmmPPPmmmmmmmmmmmmPmmk...',
      '...kpMppppppmMpMpMpMpMmpppppppppppppppppppppppppppppppppppmmk...',
      '...kpMppppppmMpMpMpMpMmpppppppppppppppppppppppppppppppppppmmk...',
      '...kpMMMMMMMmMpMpMpMpMmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmk...',
      '...kpMPPPPPPmMpMpMpMpMmPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPmmk...',
      '...kpMppppppmMpMpMpMpMmpppppppppppppppppppppppppppppppppppmmk...',
      '..kNNNNNNNNNmMpMpMpMpMmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNk..',
      '..knnKnnnnnNNNNNNNNNNNNNnnnnnKnnnnnKnnnnnKnnnnnKnnnnnKnnnnnKnk..',
      '..kKKKKKKKKNNNNNNNNNNNNNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk..',
      '..knnKnnnnnnnnnnnnnnnnnnnnnnnKnnnnnKnnnnnKnnnnnKnnnnnKnnnnnKnk..',
    ],
  ],
};

/** 3 × 3 tiles; fills the Market zone (15,6)–(17,8). */
export const objMarketStall: SpriteDef = {
  id: 'obj_market_stall',
  anchor: 'top-left',
  frames: [
    [
      '...............kPPPPPPPPPPPPPPPPk...............',
      '...............kpppmmmmmmmmmmpppk...............',
      '..kkkkkkkkkkkkkkppppppppppppppppkkkkkkkkkkkkkk..',
      '.krrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrk.',
      '.krrrrZZZZrrrrZZZZrrrrZZZZrrrrZZZZrrrrZZZZrrrrk.',
      '.kRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRk.',
      '.kRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRk.',
      '.kRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRk.',
      '.kRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRk.',
      '.kRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRk.',
      '.kRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRk.',
      '.kRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRk.',
      '.kRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRk.',
      '.kRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRk.',
      '.kRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRk.',
      '.kRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRk.',
      '.kRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRxxxxRRRRk.',
      '..krrpMZZkkrrkkZZkkrrkkZZkkrrkkZZkkrrkkZZMMrrk..',
      '...kkpMMKKKKYKKKKKKKKKKKKKKKKKKKKKKYKKKKpMMkk...',
      '....kpMMKKKKYKKKKKKKKKKKKKKKKKKKKKKYKKKKpMMk....',
      '....kpMMKKKKYKKKKKKKKKKKKKKKKKKKKKKYKKKKpMMk....',
      '....kpMMKKKKYKKKKKKKKKKKKKKKKKKKKKUuuKKKpMMk....',
      '....kpMMKKGKxGKKGKKKKKKKKKKKKKKGKKGuuGKKpMMk....',
      '....kpMMKOooOooOooKKKqKKqKKKKKKvKKvuuvKKpMMk....',
      '....kpMMKoooooooooKQQqqQQqqQQKxxxxxxxxxKpMMk....',
      '....kpMMKoooooooooKQQqqQQqqQQKxxxxxxxxxKpMMk....',
      '....kpMMKPPPPPPPPKKPPPPPPPPPKKPPPPPPPPPKpMMk....',
      '....kpMMkYPYPYPYPkkYPYPYPYPYkkYPYPYPYPYkpMMk....',
      '..kkkpMMkYYYYYYYYkkYYYYYYYYYkkYYYYYYYYYkpMMkkk..',
      '.kPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPk.',
      '.kPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPk.',
      '.kMppppppppppMppppppppppMppppppppppMppppppppppk.',
      '.kMppppppppppMppppppppppMppppppppppMppppppppppk.',
      '.kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.',
      '.kMppppppppppMppppzzzzzzzzzzzzpppppMppppppppppk.',
      '.kMppppppppppMppppzzzzzzzzzzzzpppppMppppppppppk.',
      '.kMppppppppppMppppzzKKKKKKKKzzpppppMppppppppppk.',
      '.kMMMMMMMMMMMMMMMMzzzzzzzzzzzzMMMMMMMMMMMMMMMMk.',
      '.kMppppppppppMppppzzKKKKKKzfzzpppppMppppppppppk.',
      '.kMppppppppppMppppzzzzzzzzzzzzpppppMppppppppppk.',
      '.kMppppppppppMppppppppppMppppppppppMppppppppppk.',
      '.kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.',
      '.kmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmk.',
      '..kkkpMMkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkppppppppk.',
      '.....kkk.............................kMMMmMMMMk.',
      '.....................................kMMMmMMMMk.',
      '.....................................kMMMmMMMMk.',
      '.....................................kMMMmMMMMk.',
    ],
  ],
};

/** 2 × 3 tiles, anchored at the bottom centre of its base tile. */
export const objTree: SpriteDef = {
  id: 'obj_tree',
  anchor: 'bottom-center',
  frames: [
    [
      '................................',
      '..............kkkkk.............',
      '............kkHHHHHkk...........',
      '...........kHHGLHHHGGk..........',
      '..........kHHGHHHHGGHGk.........',
      '.........kHHGHHLGGGGGHGk........',
      '.........kHHHHGGGGGgGGHk........',
      '........kHLGHGGGGGGGGHGHk.......',
      '........kHHGGGGHHgGQGGGgk.......',
      '......kkHHHGGGgGGGGGqGGggkk.....',
      '.....kHHGGHGGGgHGGGGggghgGgk....',
      '....kHGGHQGGGHGGGGgggggGggggk...',
      '...kHGGGGHqGGGGGgGggggggGggGgk..',
      '...kHGHGGGGGGGGggggggggGGggggk..',
      '..kGGGHGGHGGGGggGggghhGggGhghhk.',
      '..kHgGGGGGGGggQGGGgghgggGggghgk.',
      '..kGGGgGgGgggggqGGggggghgggghhk.',
      '..kgGGGHGggggGgggggggggGggGlhgk.',
      '..kGGGGggggggggggghghghgghghhhk.',
      '...kGGgggGgggggggggggggQhhhhhk..',
      '...kggghggGghgggGggggghhqhhghk..',
      '....kggQggggggggghGghhghhhhhk...',
      '....kgGgqggggggGggghhhlhhhhgk...',
      '....kggggGggggggghhlhhhhghhlk...',
      '...kgggggghggggghhhhhhhhhglllk..',
      '...kggggGggGgghhhhQhhhhhlllllk..',
      '...kgggghgghhghhhhhqglhllllllk..',
      '....kggGggghhhhhhhhhhlllllllk...',
      '....kgGgghhghhhhhhhlllllllllk...',
      '.....kgghhllhhhhhhlllllllllk....',
      '......khhhhghglhlllhllllllk.....',
      '.......kkhhhhhllllllllllkk......',
      '.........kkkhhlllllllkkk........',
      '............klhlllllk...........',
      '............kpmlllmk............',
      '............kpmMMMmk............',
      '............kpmMMMmk............',
      '............kpmMMMmk............',
      '............kpmMMMmk............',
      '............kpMMMMmk............',
      '............kpMMMMmk............',
      '............kpMMMMmk............',
      '............kpMMMMmk............',
      '............kpMMMMmk............',
      '...........kMpMMMMmmk...........',
      '..........kMMMMMMMMMmk..........',
      '...........kkkkkkkkkk...........',
      '................................',
    ],
  ],
};

/** A horizontal run of fence with posts every 8 px, drawn over grass. */
export const objFenceH: SpriteDef = {
  id: 'obj_fence_h',
  frames: [
    [
      '................',
      '................',
      '..kkkk....kkkk..',
      '..kPpk....kPpk..',
      'kkkPpkkkkkkPpkkk',
      'PPPPPPPPPPPPPPPP',
      'pppppppppppppppp',
      'MMMMMMMMMMMMMMMM',
      'kkkpMkkkkkkpMkkk',
      '..kpMk....kpMk..',
      'kkkpMkkkkkkpMkkk',
      'PPPPPPPPPPPPPPPP',
      'pppppppppppppppp',
      'MMMMMMMMMMMMMMMM',
      'kkkpMkkkkkkpMkkk',
      '..KKKK....KKKK..',
    ],
  ],
};

/** A vertical run of fence seen from above: a rail with square posts every 8 px. */
export const objFenceV: SpriteDef = {
  id: 'obj_fence_v',
  frames: [
    [
      '......kPMk......',
      '......kPMk......',
      '.....kkkkkk.....',
      '.....kPppMk.....',
      '.....kpppMk.....',
      '.....kMMMmk.....',
      '.....kkkkkk.....',
      '......kPMk......',
      '......kPMk......',
      '......kPMk......',
      '.....kkkkkk.....',
      '.....kPppMk.....',
      '.....kpppMk.....',
      '.....kMMMmk.....',
      '.....kkkkkk.....',
      '......kPMk......',
    ],
  ],
};

/** Wild flowers scattered on grass (no outline: they are terrain decoration). */
export const objFlowerA: SpriteDef = {
  id: 'obj_flower_a',
  frames: [
    [
      '................',
      '................',
      '................',
      '................',
      '...........I....',
      '..........IuI...',
      '....i......I....',
      '...iui.....G....',
      '....i.....hG....',
      '....G......G....',
      '....Gh..........',
      '....G....U......',
      '........UuU.....',
      '.........U......',
      '.........G......',
      '................',
    ],
  ],
};

export const objFlowerB: SpriteDef = {
  id: 'obj_flower_b',
  frames: [
    [
      '................',
      '................',
      '................',
      '......V.........',
      '.....VvV........',
      '......V....w....',
      '......G...wUw...',
      '......Gh...w....',
      '......G....G....',
      '...........Gh...',
      '..V........G....',
      '.VvV............',
      '..V.............',
      '..G.............',
      '..Gh............',
      '................',
    ],
  ],
};

/** 1 tile at (18,7): the Shipping Bin, a lidded crate with a gold coin plate (phase 03). */
export const objShippingBin: SpriteDef = {
  id: 'obj_shipping_bin',
  anchor: 'top-left',
  frames: [
    [
      '................',
      '..kkkkkkkkkkkk..',
      '.kPPPPPPPPPPPPk.',
      'kPppppppppppppPk',
      'kMMMMMMMMMMMMMMk',
      'kkkkkkkkkkkkkkkk',
      'kPpppppppppppPMk',
      'kPppppkkkkppppMk',
      'kPpppkfUfFkpppMk',
      'kPppppkkkkppppMk',
      'kMMMMMMMMMMMMMMk',
      'kPpppppppppppPMk',
      'kPpppppppppppPMk',
      'kMMMMMMMMMMMMMmk',
      '.kkkkkkkkkkkkkk.',
      '..KKKKKKKKKKKK..',
    ],
  ],
};

/** Weeds south of the starting field; cleared by the first expansion. */
export const objWeeds: SpriteDef = {
  id: 'obj_weeds',
  anchor: 'top-left',
  frames: [
    [
      '................',
      '................',
      '................',
      '.......k........',
      '......khk...k...',
      '..k...khk..khk..',
      '.khk.khhhk.khk..',
      '.khhkkhGhk.khhk.',
      '..khhhhGhkkhhk..',
      '..khGhhhhhhGhk..',
      '...khhGhhhhhk...',
      '...kkhhhhhhkk...',
      '....kkkkkkkk....',
      '................',
      '................',
      '................',
    ],
  ],
};

/** An old tree stump beside the weeds; cleared by the first expansion. */
export const objStump: SpriteDef = {
  id: 'obj_stump',
  anchor: 'top-left',
  frames: [
    [
      '................',
      '................',
      '................',
      '................',
      '................',
      '....kkkkkkkk....',
      '...kPPPPPPPPk...',
      '..kPpPPmmPPpPk..',
      '..kPPmPPPPmPPk..',
      '..kmPPPPPPPPmk..',
      '..kMmMMmMMmMMk..',
      '..kMmMMmMMmMMk..',
      '.kmMmMMmMMmMMmk.',
      'kmmkkmkkkkmkkmmk',
      '.kk..k....k..kk.',
      '................',
    ],
  ],
};

/** Flat stepping stones laid on the paths by the second expansion. */
export const objStones: SpriteDef = {
  id: 'obj_stones',
  anchor: 'top-left',
  frames: [
    [
      '................',
      '................',
      '...kkkk.........',
      '..kNNNNk........',
      '..kNNNnk........',
      '...knnk.........',
      '...........kkk..',
      '..........kNNNk.',
      '..........kNnnk.',
      '...........kkk..',
      '....kkkk........',
      '...kNNNNk.......',
      '...kNNnnk.......',
      '....kkkk........',
      '................',
      '................',
    ],
  ],
};

/** A straw-hatted scarecrow post, a decoration for the full farm (phase 04's scarecrows are placed on plots). */
export const objScarecrowPost: SpriteDef = {
  id: 'obj_scarecrow_post',
  anchor: 'bottom-center',
  frames: [
    [
      '................',
      '................',
      '................',
      '......kkkk......',
      '.....kyyyyk.....',
      '....kyYYYYyk....',
      '..kkkkkkkkkkkk..',
      '..kyyyyyyyyyyk..',
      '...kkkxxxxkkk...',
      '.....kxkkxk.....',
      '.....kxxxxk.....',
      '......kkkk......',
      'kkkkkkkqqkkkkkkk',
      'kyyqqqqqqqqqqyyk',
      'kkkkqqQqqQqqkkkk',
      '...kqqqqqqqqk...',
      '...kqqQqqQqqk...',
      '...kqqqqqqqqk...',
      '...kkkkMmkkkk...',
      '......kMmk......',
      '......kMmk......',
      '......kMmk......',
      '......kMmk......',
      '......kMmk......',
      '......kMmk......',
      '......kMmk......',
      '......kMmk......',
      '......kMmk......',
      '......kMmk......',
      '......kMmk......',
      '.....kMMmmk.....',
      '.....kkkkkk.....',
    ],
  ],
};
